language: python

python:
  - "3.5"

sudo: required

dist: trusty

env:
  matrix:
    - TEST_ENV=test
    - TEST_ENV=check

install:
  # pip-tools depends on this version
  - "pip install --upgrade pip==8.1.1"

  - make system_requirements
  - pip install -r requirements/travis.txt

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - echo "TEST_ENV=$TEST_ENV"
  - |
    set -e
    case "$TEST_ENV" in
      test)
        make test ;;
      check)
        make check ;;
      *)
        echo "Unknown TEST_ENV: $TEST_ENV."
        exit 1;;
    esac

notifications:
  email: false
